import Logo from "./Logos/Logo.png";
import Avatar from "./Avatar/avatar.png";
import clinca_logo from "./Logos/clinca_logo.png";
import Darklogo from "./Logos/Darklogo.png"
import Lightlogo from "./Logos/Lightlogo.png"
import Image404 from './404-mcm.png'
import Eng from "./Logos/Eng.png"
import Esp from "./Logos/Esp.png"
import Group47 from "./Logos/Group47.png"
import Group52 from "./Logos/Group52.png"
import Group44 from "./Logos/Group44.png"
import Globe from "./Logos/Globe.png"
import Group53 from "./Logos/Group53.png"
import blueshade from "./Logos/blueshade.png"
import Ellipse from "./Logos/Ellipse.png"
import Vector from "./Logos/Vector.png"
import Group193 from "./Logos/Group193.png"
import Group198 from "./Logos/Group198.png"
export { Logo, Avatar, clinca_logo, Darklogo, Lightlogo, Image404, Eng, Esp, Group47, Group44, Group52, Globe, Group53, blueshade, Ellipse, Vector, Group193, Group198 };
