"use client";
import React, { useContext, useEffect, useState } from "react";
import { Spinner } from "flowbite-react";
import moment from "moment";
import {
  create_content_service,
  delete_content_service,
  fetch_content_service,
  update_content_service,
} from "@/utils/supabase/data_services/data_services";
import { PiCaretUpDownBold } from "react-icons/pi";
import { Custom_Modal } from "@/components/Modal_Components/Custom_Modal";
import { Input_Component } from "@/components/Input_Component";
import { Action_Button } from "@/components/Action_Button";
import { toast } from "react-toastify";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useTranslation } from "react-i18next";
import { translationConstant } from "@/utils/translationConstants";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Slidercomp } from "@/components/sliderComp";
import { TabContext } from "@/context";
import {
  EyeIcon,
  PencilIcon,
  PlusCircle,
  Search,
  TrashIcon,
} from "lucide-react";

const fields = [
  {
    id: "id",
    label: "Promo id",
    type: "number",
    autoGenerated: true,
    editable: false,
    table_column: false,
    details_section: false,
    details_order: 0,
  },
  {
    id: "active",
    label: "Procode_k4",
    type: "boolean",
    editable: false,
    table_column: true,
    details_section: true,
    render_value: (val: boolean) => (val ? "Active" : "In-active"),
    align: "text-start",
    details_order: 3,
  },
  {
    id: "typename",
    label: "Procode_k5",
    details_label: "Procode_k9",
    type: "text",
    editable: true,
    table_column: true,
    details_section: true,
    details_order: 1,
  },
  {
    id: "multiple",
    label: "Procode_k12",
    type: "boolean",
    editable: true,
    table_column: false,
    details_section: true,
    render_value: (val: boolean) => (val ? "True" : "False"),
    details_order: 4,
  },
  {
    id: "percentage",
    label: "Procode_k6",
    type: "number",
    editable: true,
    table_column: true,
    details_section: true,
    render_value: (val: number) => `${val}%`,
    details_order: 2,
    col_span_01_modal: true,
    max: 100,
  },
  {
    id: "expiry",
    label: "Procode_k7",
    type: "date",
    editable: true,
    table_column: true,
    details_section: true,
    render_value: (val: string) =>
      moment(val, "YYYY-MM-DD h:mm s").format("MM/DD/YYYY"),
    min: moment(new Date()).format("YYYY-MM-DD"),
    align: "text-end",
    details_order: 5,
    col_span_01: true,
  },
  {
    id: "created_at",
    label: "Procode_k14",
    type: "date",
    editable: false,
    table_column: false,
    details_section: true,
    render_value: (val: string) =>
      moment(val, "YYYY-MM-DD h:mm:s").utc().format("MM/DD/YYYY"),
    details_order: 6,
    col_span_01: true,
  },
];

interface DataListInterface {
  [x: string]: any;
  id: number;
  typename: string;
  active: boolean;
  multiple: boolean;
  percentage: number;
  expiry: string;
  created_at: string;
}

function removeDuplicates(array: DataListInterface[]): DataListInterface[] {
  const seenIds = new Set<number>();
  return array.filter((element) => {
    if (!seenIds.has(element.id)) {
      seenIds.add(element.id);
      return true;
    }
    return false;
  });
}

const modal_titles: any = {
  create: {
    modalLabel: "Create New Promocode",
    button: {
      label: "Create Promocode",
      color: "blue",
    },
  },
  edit: {
    modalLabel: "Edit Promocode",
    button: {
      label: "Update Promocode",
      color: "info",
    },
  },
  delete: {
    modalLabel: "Delete Promocode Confirmation",
    button: {
      label: "Delete Promocode",
      color: "failure",
    },
  },
};

const Page = () => {
  const [dataList, setDataList] = useState<DataListInterface[]>([]);
  const [allData, setAllData] = useState<DataListInterface[]>([]);
  const [detailsView, setDetailsView] = useState<DataListInterface | null>(null);
  const [loading, setLoading] = useState(true);
  const [sortOrder, setSortOrder] = useState(-1);
  const [sortColumn, setSortColumn] = useState("");
  const [isOpenModal, setIsOpenModal] = useState(false);
  const [activeModalMode, setActiveModalMode] = useState<"edit" | "delete" | "create" | "">("");
  const [newDetails, setNewDetails] = useState<any>({});
  const [modalLoading, setModalLoading] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const ITEMS_PER_PAGE = 5;
  const totalPages = Math.ceil(dataList.length / ITEMS_PER_PAGE);
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE;
  const endIndex = Math.min(startIndex + ITEMS_PER_PAGE, dataList.length);
  const currentData = dataList.slice(startIndex, endIndex);

  useEffect(() => {
    const savedMode = localStorage.getItem("darkMode");
    if (savedMode !== null) {
      setDarkMode(savedMode === "true");
    } else {
      setDarkMode(window.matchMedia("(prefers-color-scheme: dark)").matches);
    }
  }, []);

  const openModalHandle = () => {
    setIsOpenModal(true);
  };
  const closeModalHandle = () => {
    setIsOpenModal(false);
    setNewDetails({});
    setActiveModalMode("");
  };

  const onChangeHandle = (e: any) => {
    const val = e.target.value;
    if (val === "") {
      setDataList([...allData]);
    } else {
      const filteredData = allData.filter((elem) =>
        elem.typename.toLowerCase().includes(val.toLowerCase())
      );
      setDataList([...filteredData]);
    }
  };

  const detailsViewHandle = (param_data: DataListInterface) => {
    setDetailsView(param_data);
  };

  const fetch_handle = async () => {
    setLoading(true);
    try {
      const fetched_data: any = await fetch_content_service({
        table: "promotype",
      });
      setDataList(fetched_data || []);
      setAllData(fetched_data || []);
    } catch (error) {
      console.error("Fetch error:", error);
      toast.error("Failed to fetch data");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetch_handle();
  }, []);

  const sortHandle = (column: string, type: string) => {
    let sortedList: DataListInterface[] = [...dataList];
    if (type === "text") {
      sortedList.sort((a, b) =>
        sortOrder === 1
          ? a[column].localeCompare(b[column])
          : b[column].localeCompare(a[column])
      );
    } else if (type === "date") {
      sortedList.sort((a, b) =>
        sortOrder === 1
          ? new Date(a[column]).getTime() - new Date(b[column]).getTime()
          : new Date(b[column]).getTime() - new Date(a[column]).getTime()
      );
    } else {
      sortedList.sort((a, b) =>
        sortOrder === 1 ? a[column] - b[column] : b[column] - a[column]
      );
    }
    setSortOrder((order) => (order === -1 ? 1 : -1));
    setDataList([...sortedList]);
    setSortColumn(column);
  };

  const modalInputChangeHandle = (e: string, id: string) => {
    setNewDetails((prev: any) => ({ ...prev, [id]: e }));
  };

  const createNewDataHandle = async () => {
    setModalLoading(true);
    try {
      const { data: res_data, error } = await create_content_service({
        table: "promotype",
        language: "",
        post_data: newDetails,
      });
      if (error) {
        console.error("Create error:", error.message);
        toast.error(error.message);
        return;
      }
      if (res_data?.length) {
        toast.success("Created successfully");
        closeModalHandle();
        const newDataList = [res_data[0], ...dataList];
        const newAllData = [res_data[0], ...allData];
        setDataList(removeDuplicates(newDataList));
        setAllData(removeDuplicates(newAllData));
      }
    } catch (error) {
      console.error("Create error:", error);
      toast.error("Failed to create promocode");
    } finally {
      setModalLoading(false);
    }
  };

  const deleteDataHandle = async () => {
    setModalLoading(true);
    try {
      const selectedId = newDetails?.id || detailsView?.id;
      if (!selectedId) {
        toast.error("No item selected for deletion");
        return;
      }
      const { error } = await delete_content_service({
        table: "promotype",
        id: selectedId,
      });
      if (error) {
        console.error("Delete error:", error.message);
        toast.error(error.message);
        return;
      }
      setDataList((list) => list.filter((data) => data.id !== selectedId));
      setAllData((list) => list.filter((data) => data.id !== selectedId));
      if (detailsView?.id === selectedId) {
        setDetailsView(null);
      }
      toast.success("Deleted successfully");
      closeModalHandle();
    } catch (error) {
      console.error("Delete error:", error);
      toast.error("Failed to delete promocode");
    } finally {
      setModalLoading(false);
    }
  };

  const editDataHandle = async () => {
    setModalLoading(true);
    try {
      const data = await update_content_service({
        table: "promotype",
        language: "",
        post_data: newDetails,
      });
      if (data?.length) {
        toast.success("Updated successfully");
        closeModalHandle();
        const newData = data[0];
        setDataList((list) =>
          list.map((elem) => (elem.id === newData.id ? newData : elem))
        );
        setAllData((list) =>
          list.map((elem) => (elem.id === newData.id ? newData : elem))
        );
        setDetailsView(newData);
      }
    } catch (error: any) {
      console.error("Update error:", error);
      toast.error(error?.message || "Failed to update promocode");
    } finally {
      setModalLoading(false);
    }
  };

  const modalSubmitHandle = async () => {
    switch (activeModalMode) {
      case "create":
        await createNewDataHandle();
        break;
      case "edit":
        await editDataHandle();
        break;
      case "delete":
        await deleteDataHandle();
        break;
    }
  };

  const addNewHandle = () => {
    openModalHandle();
    setActiveModalMode("create");
  };

  const editHandle = () => {
    if (detailsView) {
      setNewDetails(detailsView);
      setActiveModalMode("edit");
      openModalHandle();
    }
  };

  const deleteHandle = () => {
    if (detailsView) {
      setNewDetails(detailsView);
      setActiveModalMode("delete");
      openModalHandle();
    }
  };

  const { setActiveTitle } = useContext(TabContext);

  useEffect(() => {
    setActiveTitle("Sidebar_k16");
  }, []);

  const { t } = useTranslation(translationConstant.PROCODE);

  const handlePreviousPage = () => {
    setCurrentPage((prev) => Math.max(prev - 1, 1));
  };

  const handleNextPage = () => {
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));
  };

  return (
    <main className="w-full h-full font-[500] text-[20px] dark:bg-gray-900 dark:text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center py-2">
          <h1 className="text-xl font-bold dark:text-white">{t("Procode_k1")}</h1>
        </div>

        <div className="w-full min-h-[84dvh] py-2 flex flex-col gap-2">
          <div className="space-y-6 pb-4 flex justify-between mt-3">
            <div className="flex justify-between items-center w-full">
              <div className="relative w-full max-w-xs">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 w-4 h-4" />
                <input
                  onChange={onChangeHandle}
                  type="text"
                  placeholder={t("Procode_k3")}
                  className="w-full py-3 pl-10 pr-3 text-sm rounded-md focus:outline-none bg-[#f1f4f9] dark:bg-gray-800 dark:border-gray-700 dark:text-white"
                />
              </div>
              <button
                onClick={addNewHandle}
                className="bg-[#0066ff] text-sm text-white px-5 py-2 rounded-md hover:opacity-70 active:opacity-90 dark:hover:bg-blue-700 dark:active:bg-blue-800 flex items-center gap-2"
              >
                <PlusCircle className="w-4 h-4" />
                {t("Procode_k2")} Promo Code
              </button>
            </div>
          </div>

          <div className="overflow-y-auto max-h-[calc(84dvh-150px)]">
            {/* Table for medium and larger screens */}
            <div className="hidden md:block rounded-lg border border-gray-200 dark:border-[#172945]">
              <Table className="w-full">
                <TableHeader>
                  <TableRow className="dark:border-gray-700">
                    {fields
                      .filter(({ table_column }) => table_column)
                      .map(({ id, label, align, type }, ind) => (
                        <TableHead
                          key={ind}
                          className={`${
                            align || "text-left"
                          } text-[#71717A] dark:text-gray-300 font-medium text-lg px-4 py-2 border-b border-gray-300 dark:border-gray-700`}
                        >
                          {t(label)}
                          <button
                            onClick={() => sortHandle(id, type)}
                            className="active:opacity-50 ml-1"
                          >
                            <PiCaretUpDownBold
                              className={`inline ${
                                sortColumn === id
                                  ? "text-green-600 dark:text-green-400"
                                  : "text-gray-400/50 dark:text-gray-500"
                              } hover:text-gray-600 dark:hover:text-gray-300 active:text-gray-500`}
                            />
                          </button>
                        </TableHead>
                      ))}
                    <TableHead className="text-left text-[#71717A] dark:text-gray-300 font-medium text-lg px-4 py-2 border-b border-gray-300 dark:border-gray-700">
                      Actions
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {loading ? (
                    <TableRow>
                      <TableCell
                        colSpan={fields.filter((f) => f.table_column).length + 1}
                        className="dark:bg-gray-800"
                      >
                        <div className="flex h-64 justify-center items-center">
                          <Spinner size="xl" />
                        </div>
                      </TableCell>
                    </TableRow>
                  ) : dataList.length > 0 ? (
                    currentData.map((elem) => (
                      <TableRow
                        key={elem.id}
                        className="hover:bg-gray-50 cursor-pointer border-b border-gray-300 dark:border-gray-700"
                        onClick={() => detailsViewHandle(elem)}
                      >
                        {fields
                          .filter(({ table_column }) => table_column)
                          .map(({ id: fieldKey, align, render_value }) => {
                            const extract_val = render_value
                              //@ts-ignore
                              ? render_value(elem[fieldKey])
                              : elem[fieldKey];
                            return (
                              <TableCell
                                key={fieldKey}
                                className={`${
                                  align || "text-left"
                                } font-normal text-base px-5 py-3 dark:text-white dark:bg-[#111827]`}
                              >
                                {fieldKey === "active" ? (
                                  <span
                                    className={`px-2 py-1 rounded-full text-xs font-semibold ${
                                      extract_val === "Active"
                                        ? "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-100"
                                        : "bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-100"
                                    }`}
                                  >
                                    {extract_val}
                                  </span>
                                ) : (
                                  extract_val
                                )}
                              </TableCell>
                            );
                          })}
                        <TableCell className="text-left px-4 py-2 space-x-2 dark:bg-[#111827]">
                          <EyeIcon
                            className="text-gray-500 hover:text-black dark:hover:text-white w-4 h-4 inline cursor-pointer"
                            onClick={(e) => {
                              e.stopPropagation();
                              detailsViewHandle(elem);
                            }}
                          />
                          <PencilIcon
                            className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 w-4 h-4 inline cursor-pointer ml-2"
                            onClick={(e) => {
                              e.stopPropagation();
                              setNewDetails(elem);
                              setActiveModalMode("edit");
                              setIsOpenModal(true);
                            }}
                          />
                          <TrashIcon
                            className="text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 w-4 h-4 inline cursor-pointer ml-2"
                            onClick={(e) => {
                              e.stopPropagation();
                              setNewDetails(elem);
                              setActiveModalMode("delete");
                              setIsOpenModal(true);
                            }}
                          />
                        </TableCell>
                      </TableRow>
                    ))
                  ) : (
                    <TableRow>
                      <TableCell
                        colSpan={fields.filter((f) => f.table_column).length + 1}
                        className="dark:bg-[#111827]"
                      >
                        <div className="flex h-64 justify-center items-center">
                          <h1 className="dark:text-white">No Data found!</h1>
                        </div>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </div>

            {/* Cards for small screens */}
            <div className="md:hidden grid gap-4">
              {loading ? (
                <div className="flex justify-center items-center h-64">
                  <Spinner size="xl" />
                </div>
              ) : dataList.length > 0 ? (
                currentData.map((elem) => (
                  <div
                    key={elem.id}
                    className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 bg-white dark:bg-gray-800 shadow-sm cursor-pointer"
                    onClick={() => detailsViewHandle(elem)}
                  >
                    <div className="space-y-3">
                      {fields
                        .filter(({ table_column }) => table_column)
                        .map(({ id: fieldKey, label, render_value }) => {
                          const extract_val = render_value
                          //@ts-ignore
                            ? render_value(elem[fieldKey])
                            : elem[fieldKey];
                          return (
                            <div key={fieldKey} className="flex justify-between items-center">
                              <span className="text-sm text-gray-600 dark:text-gray-300">{t(label)}:</span>
                              <span className="text-sm font-medium dark:text-white max-w-[60%] text-right">
                                {fieldKey === "active" ? (
                                  <span
                                    className={`px-2 py-1 rounded-full text-xs font-semibold ${
                                      extract_val === "Active"
                                        ? "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-100"
                                        : "bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-100"
                                    }`}
                                  >
                                    {extract_val}
                                  </span>
                                ) : (
                                  extract_val
                                )}
                              </span>
                            </div>
                          );
                        })}
                      <div className="flex justify-end gap-2 pt-2">
                        <EyeIcon
                          className="text-gray-500 hover:text-black dark:hover:text-white w-4 h-4 cursor-pointer"
                          onClick={(e) => {
                            e.stopPropagation();
                            detailsViewHandle(elem);
                          }}
                        />
                        <PencilIcon
                          className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 w-4 h-4 cursor-pointer"
                          onClick={(e) => {
                            e.stopPropagation();
                            setNewDetails(elem);
                            setActiveModalMode("edit");
                            setIsOpenModal(true);
                          }}
                        />
                        <TrashIcon
                          className="text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 w-4 h-4 cursor-pointer"
                          onClick={(e) => {
                            e.stopPropagation();
                            setNewDetails(elem);
                            setActiveModalMode("delete");
                            setIsOpenModal(true);
                          }}
                        />
                      </div>
                    </div>
                  </div>
                ))
              ) : (
                <div className="flex justify-center items-center h-64">
                  <h1 className="dark:text-white">No Data found!</h1>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between mt-4 px-2">
              <p className="text-sm text-muted-foreground dark:text-gray-300">
                {dataList.length === 0
                  ? "Showing 0 to 0 of 0 results"
                  : `Showing ${startIndex + 1} to ${endIndex} of ${dataList.length} results`}
              </p>
              <div className="flex space-x-2">
                <button
                  onClick={handlePreviousPage}
                  disabled={currentPage === 1}
                  className={`text-sm border rounded px-3 py-1 hover:bg-gray-100 dark:border-gray-600 dark:hover:bg-gray-700 dark:text-white ${
                    currentPage === 1 ? "opacity-50 cursor-not-allowed" : ""
                  }`}
                >
                  Previous
                </button>
                <button
                  onClick={handleNextPage}
                  disabled={currentPage === totalPages || dataList.length === 0}
                  className={`text-sm border rounded px-3 py-1 hover:bg-gray-100 dark:border-gray-600 dark:hover:bg-gray-700 dark:text-white ${
                    currentPage === totalPages || dataList.length === 0
                      ? "opacity-50 cursor-not-allowed"
                      : ""
                  }`}
                >
                  Next
                </button>
              </div>
            </div>
          </div>
        </div>

        <Sheet
          open={!!detailsView}
          onOpenChange={(open) => !open && setDetailsView(null)}
        >
          <SheetContent className="p-0 pt-10 dark:bg-gray-800 dark:border-gray-700">
            <div className="flex flex-col h-full">
              <div className="px-4 pt-2 pb-3">
                <SheetHeader className="sr-only">
                  <SheetTitle className="dark:text-white">{t("Procode_k8")}</SheetTitle>
                </SheetHeader>
                <h1 className="text-xl font-bold dark:text-white">{t("Procode_k8")}</h1>
              </div>

              {detailsView && (
                <div className="flex-1 overflow-auto px-4">
                  <div className="grid grid-cols-2 gap-y-6">
                    {fields
                      .filter(({ details_section }) => details_section)
                      .sort((a, b) => a.details_order - b.details_order)
                      .map((field, ind) => {
                        const extract_val = field.render_value
                          // @ts-ignore
                          ? field.render_value(detailsView[field.id])
                          : detailsView[field.id];
                        return (
                          <div
                            key={ind}
                            className={field.col_span_01 ? "col-span-1" : "col-span-2"}
                          >
                            <div>
                              <h1 className="text-sm text-gray-600 dark:text-gray-300">
                                {t(field.details_label || field.label)}
                              </h1>
                              <p className="font-medium text-base dark:text-white">
                                {extract_val || "N/A"}
                              </p>
                            </div>
                          </div>
                        );
                      })}
                  </div>

                  <div className="flex gap-4 pt-8 pb-4">
                    <Action_Button
                      onClick={editHandle}
                      width="w-full"
                      height="h-12"
                      label={t("Procode_k15")}
                      bg_color="bg-[#0066ff] dark:bg-blue-700"
                      border="#0066ff dark:border-blue-700"
                    />
                    <Action_Button
                      onClick={deleteHandle}
                      width="w-full"
                      height="h-12"
                      label={t("Procode_k16")}
                      bg_color="bg-[#FFD2CC] dark:bg-red-900"
                      border="#FFD2CC dark:border-red-900"
                    />
                  </div>
                </div>
              )}
            </div>
          </SheetContent>
        </Sheet>

        <Custom_Modal
          submit_button_color={modal_titles[activeModalMode]?.button?.color}
          loading={modalLoading}
          buttonLabel={modal_titles[activeModalMode]?.button?.label}
          is_open={isOpenModal}
          Title={activeModalMode && modal_titles[activeModalMode]?.modalLabel}
          close_handle={closeModalHandle}
          open_handle={openModalHandle}
          create_new_handle={modalSubmitHandle}
          darkMode={darkMode}
        >
          {activeModalMode === "delete" ? (
            <div className="dark:text-white">
              <h1>Are you sure you want to delete this Promocode?</h1>
            </div>
          ) : (
            <form className="grid grid-cols-2 gap-4">
              {fields
                .filter(({ editable }) => editable)
                .map(({ id, label, type, col_span_01, col_span_01_modal, min, max }) => (
                  <div
                    key={id}
                    className={`col-span-${col_span_01 || col_span_01_modal ? "1" : "2"} flex flex-col gap-1`}
                  >
                    {id === "percentage" ? (
                      <div className="flex flex-col w-full">
                        <label className="text-base font-semibold mb-4 dark:text-white">
                          Percentage
                        </label>
                        <Slidercomp
                          className="w-full"
                          value={newDetails ? newDetails[id] : ""}
                          // @ts-ignore
                          onChange={(e: string) => modalInputChangeHandle(e, id)}
                          darkMode={darkMode}
                        />
                      </div>
                    ) : (
                      <Input_Component
                        min={min || ""}
                        // @ts-ignore
                        max={max || ""}
                        value={newDetails ? newDetails[id] : ""}
                        type={type}
                        border="border-2 border-gray-300 dark:border-gray-600 rounded-md w-full"
                        onChange={(e: string) => modalInputChangeHandle(e, id)}
                        label={t(label)}
                        isDate={type === "date"}
                        darkMode={darkMode}
                      />
                    )}
                  </div>
                ))}
            </form>
          )}
        </Custom_Modal>
      </div>
    </main>
  );
};

export default Page;