revoke delete on table "public"."sample_feature2" from "anon";

revoke insert on table "public"."sample_feature2" from "anon";

revoke references on table "public"."sample_feature2" from "anon";

revoke select on table "public"."sample_feature2" from "anon";

revoke trigger on table "public"."sample_feature2" from "anon";

revoke truncate on table "public"."sample_feature2" from "anon";

revoke update on table "public"."sample_feature2" from "anon";

revoke delete on table "public"."sample_feature2" from "authenticated";

revoke insert on table "public"."sample_feature2" from "authenticated";

revoke references on table "public"."sample_feature2" from "authenticated";

revoke select on table "public"."sample_feature2" from "authenticated";

revoke trigger on table "public"."sample_feature2" from "authenticated";

revoke truncate on table "public"."sample_feature2" from "authenticated";

revoke update on table "public"."sample_feature2" from "authenticated";

revoke delete on table "public"."sample_feature2" from "service_role";

revoke insert on table "public"."sample_feature2" from "service_role";

revoke references on table "public"."sample_feature2" from "service_role";

revoke select on table "public"."sample_feature2" from "service_role";

revoke trigger on table "public"."sample_feature2" from "service_role";

revoke truncate on table "public"."sample_feature2" from "service_role";

revoke update on table "public"."sample_feature2" from "service_role";

alter table "public"."sample_feature2" drop constraint "sample_feature2_pkey";

drop index if exists "public"."sample_feature2_pkey";

drop table "public"."sample_feature2";


  create table "public"."sample" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."sample" enable row level security;


  create table "public"."sample_features" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "description" text,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "new_col" text,
    "debug_check" boolean default false
      );


alter table "public"."sample_features" enable row level security;

CREATE INDEX idx_sample_features_is_active ON public.sample_features USING btree (is_active);

CREATE UNIQUE INDEX sample_features_pkey ON public.sample_features USING btree (id);

CREATE UNIQUE INDEX sample_pkey ON public.sample USING btree (id);

alter table "public"."sample" add constraint "sample_pkey" PRIMARY KEY using index "sample_pkey";

alter table "public"."sample_features" add constraint "sample_features_pkey" PRIMARY KEY using index "sample_features_pkey";

grant delete on table "public"."sample" to "anon";

grant insert on table "public"."sample" to "anon";

grant references on table "public"."sample" to "anon";

grant select on table "public"."sample" to "anon";

grant trigger on table "public"."sample" to "anon";

grant truncate on table "public"."sample" to "anon";

grant update on table "public"."sample" to "anon";

grant delete on table "public"."sample" to "authenticated";

grant insert on table "public"."sample" to "authenticated";

grant references on table "public"."sample" to "authenticated";

grant select on table "public"."sample" to "authenticated";

grant trigger on table "public"."sample" to "authenticated";

grant truncate on table "public"."sample" to "authenticated";

grant update on table "public"."sample" to "authenticated";

grant delete on table "public"."sample" to "service_role";

grant insert on table "public"."sample" to "service_role";

grant references on table "public"."sample" to "service_role";

grant select on table "public"."sample" to "service_role";

grant trigger on table "public"."sample" to "service_role";

grant truncate on table "public"."sample" to "service_role";

grant update on table "public"."sample" to "service_role";

grant delete on table "public"."sample_features" to "anon";

grant insert on table "public"."sample_features" to "anon";

grant references on table "public"."sample_features" to "anon";

grant select on table "public"."sample_features" to "anon";

grant trigger on table "public"."sample_features" to "anon";

grant truncate on table "public"."sample_features" to "anon";

grant update on table "public"."sample_features" to "anon";

grant delete on table "public"."sample_features" to "authenticated";

grant insert on table "public"."sample_features" to "authenticated";

grant references on table "public"."sample_features" to "authenticated";

grant select on table "public"."sample_features" to "authenticated";

grant trigger on table "public"."sample_features" to "authenticated";

grant truncate on table "public"."sample_features" to "authenticated";

grant update on table "public"."sample_features" to "authenticated";

grant delete on table "public"."sample_features" to "service_role";

grant insert on table "public"."sample_features" to "service_role";

grant references on table "public"."sample_features" to "service_role";

grant select on table "public"."sample_features" to "service_role";

grant trigger on table "public"."sample_features" to "service_role";

grant truncate on table "public"."sample_features" to "service_role";

grant update on table "public"."sample_features" to "service_role";


  create policy "allow read to all"
  on "public"."sample_features"
  as permissive
  for select
  to public
using (true);



