-- =====================
-- ENUMS
-- =====================
create type if not exists public.block_type
as enum ('heading','paragraph','list','table','field','signature','spacer');

create type if not exists public.encounter_status
as enum (
  'appointment_initiated',
  'provider_assigned',
  'vitals_assessed',
  'in_consultation',
  'consultation_concluded',
  'final_review',
  'completed'
);

create type if not exists public.exam_status_enum
as enum ('Never','Don’t remember','Month & Year');

create type if not exists public.form_type
as enum ('telemedicine','hipaa','surgery');

-- =====================
-- NEW TABLES
-- =====================
create table if not exists public.forms (
  id bigint generated always as identity primary key,
  name text not null,
  is_active boolean default true,
  created_at timestamptz default now(),
  content jsonb
);

alter table public.forms enable row level security;

create table if not exists public.signed_form (
  id bigint generated always as identity primary key,
  appointment_id bigint,
  telemedicine_form_path text,
  hipaacompliance_form_path text,
  generalsurgery_form_path text
);

alter table public.signed_form enable row level security;

alter table public.signed_form
add constraint if not exists signed_form_appointment_id_fkey
foreign key (appointment_id)
references public."Appoinments"(id)
on delete cascade;

create table if not exists public.special_picture (
  id bigint generated by default as identity primary key,
  file_path text not null,
  display boolean not null default false,
  created_at timestamptz not null default now(),
  title text
);

alter table public.special_picture enable row level security;

-- =====================
-- COLUMN ADDITIONS
-- =====================
alter table public."Appoinments"
add column if not exists signed_form_path text;

alter table public."Appoinments"
add column if not exists status public.encounter_status
default 'appointment_initiated';

alter table public.intake_form
add column if not exists birth_control varchar(20),
add column if not exists last_pap_smear_month_year varchar(20),
add column if not exists last_pap_smear_status public.exam_status_enum,
add column if not exists last_prostate_exam_month_year varchar(20),
add column if not exists last_prostate_exam_status public.exam_status_enum,
add column if not exists mammography_month_year varchar(20),
add column if not exists mammography_status public.exam_status_enum,
add column if not exists number_of_pregnancies integer;

alter table public.profiles
add column if not exists availability boolean not null default false,
add column if not exists user_type text;

-- =====================
-- RLS POLICIES (INTENTIONAL)
-- =====================
create policy if not exists "forms_select_public"
on public.forms
for select
to anon, authenticated
using (true);

create policy if not exists "signed_form_all_access"
on public.signed_form
for all
to public
using (true)
with check (true);

create policy if not exists "public_read_special_picture"
on public.special_picture
for select
to public
using (true);
